# ==============================================================================
# ⚠️ SECURITY WARNING: 
# Committing this file to GitHub exposes your database passwords and API keys! 
# Base64 is NOT encryption. 
# In a real production setup, use a Secret Manager (like AWS Secrets Manager) 
# or create the Kubernetes Secret directly from Jenkins using credentials. 
# For learning purposes, ensure your repository is **PRIVATE**.
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: ecom-secrets
  namespace: ecom-production
type: Opaque
data:
  CLOUDINARY_API_SECRET: eFRPdzVaRnJkc1BmaE81TldqaWVyeVVHU2tn
  MAIL_PASSWORD: ZnlrcGNsZGtzc2JqZnR6eg==
  NODE_ENV: cHJvZHVjdGlvbg==
  CLOUDINARY_CLOUD_NAME: ZGtwb2EyNmRr
  CLOUDINARY_API_KEY: ODM4MzYzNjk5NzQ1Njg1
  STRIPE_WEBHOOK_KEY: d2hzZWNfYjlhYWM1MGNlZWYzN2YyNmJiODQ3ODI0YjVkZTQ5MmY3MzdiYzQ4MWIzYzE2NWMzMjllODY3NmY0NDJhYzJjMg==
  FrontendUrl: aHR0cHM6Ly9lY29tLXRoZXRhLXNub3d5LnZlcmNlbC5hcHA=
  PORT: NTAwMA==
  STRIPE_KEY: c2tfdGVzdF81MU9yemQ3U0VGVDVSOFExbzBIdHdqWnVYbXg3S3lsM0k1bnNLZkpDY1BLU1lrNlE1MkpTR2V1Rmdma3AyVHNsN1RFU0hYblVTelAxb1lUUTBWRTZHUUhPRjAwZmg5THowQzI=
  MONGO_URI: bW9uZ29kYitzcnY6Ly9zYTp4ZjFGcjY1QWZScm8zbnRLQGNsdXN0ZXIwLjVxd3c1Lm1vbmdvZGIubmV0L2Vjb21OZXc=
  JWT_SECRET: RUNPTU1FUkNFX1NFQ1JFVA==
  MAIL_APP: cm5pc2hhbnQ0MjhAZ21haWwuY29t
