apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: monitoring # Prometheus Operator usually only looks in its own namespace
  labels:
    release: prometheus 
spec:
  namespaceSelector:
    matchNames:
      - ecom-production
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: "http-api"
    path: /metrics
    interval: 15s
